# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 20:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20180205_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='miriam',
            field=models.TextField(default=datetime.datetime(2018, 3, 4, 20, 38, 34, 861891, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
